### Test Business Registration Backend Endpoint
POST http://localhost:5000/appointments/business/register HTTP/1.1
Content-Type: application/json

{
  "name": "Test Frontend Shop",
  "businessType": "salon_spa",
  "city": "Mehsana",
  "opens": "10:00 AM",
  "closes": "09:00 PM",
  "servicesProvided": "Haircut, Styling",
  "telegramBotToken": "MOCK_TOKEN_123456"
}